
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.93.125.10:3306/forum
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 47.93.125.10
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 5000
  application:
    name: rabbitmq-hello
  rabbitmq:
    host: 47.93.125.10
    port: 5672
    username: admin
    password: 123456
  data:
    elasticsearch:
      client:
        reactive:
          username: elasticsearch
          endpoints: 47.93.125.10:9300
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://admin:123456@47.93.125.10:27017/forum

server:
  port: 8070

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
